### ISSUE TITLE
修改 Git 配置加速 clone GitHub 源码 - 宝硕博客

### ISSUE THREAD

**Issue by renbaoshuo** [renbaoshuo/blog#13]
https://baoshuo.blog/post/5vwyjylHh/

**Comment by DoraMoed** [comment]
其实懒人还可以使用暴力猴/油猴 中现成的镜像插件

**Comment by imgzkshuo221** [comment]
可以使用GitHub的香港节点 : `151.101.76.133 raw.githubusercontent.com`
