### ISSUE TITLE
什么是 DDoS？如何使用 DDoS 提升群友网站速度？ - 宝硕博客

### ISSUE THREAD

**Issue by renbaoshuo** [renbaoshuo/blog#4]
https://baoshuo.ren/post/ObCitOBoi/

**Comment by KDreamelf** [comment]
请问防火墙能分享下吗？

**Comment by renbaoshuo** [comment]
> @KDreamelf
> 请问防火墙能分享下吗？

`Pro` 版的 CloudFlare 自带的， `Free` 的也不是没有，就是功能少了点。

**Comment by chiuyau** [comment]
> @renbaoshuo
> > @KDreamelf
> > 请问防火墙能分享下吗？
> 
> `Pro` 版的 CloudFlare 自带的， `Free` 的也不是没有，就是功能少了点。

哇，居然是 Pro。有钱人

**Comment by ZC-TigerRoot** [comment]
> @chiuyau
> > @renbaoshuo
> > > @KDreamelf
> > > 请问防火墙能分享下吗？
> > 
> > `Pro` 版的 CloudFlare 自带的， `Free` 的也不是没有，就是功能少了点。
> 
> 哇，居然是 Pro。有钱人

pro可以用Plesk面板白嫖的，但是记得备份DNS解析

~~不要问我为什么……~~
