### ISSUE TITLE
友情链接 - 宝硕博客

### ISSUE THREAD

**Issue by renbaoshuo** [renbaoshuo/blog#7]
https://baoshuo.blog/friends/

**Comment by Borber** [comment]
本站标题 BORBER
本站简介 跌宕歌词 纵横书卷 不与遣年华
头像地址 https://cdn.jsdelivr.net/gh/Borber/PublicPic1/headImg/head.png
博客地址 https://borber.cn
已加贵站

**Comment by renbaoshuo** [comment]
已加，将在下次更新文章时生效。




-->
Ren Baoshuo (任宝硕)
i@baoshuo.ren
baoshuo.ren
China


Information Security Notice: This email together with its attachment(s) contain privileged or confidential information. If you are not the intended recipient or you are unauthorized person, please do not read, save, print, copy, retransmit, publish or otherwise use the information of this email and the attachment(s).  The information contained in this mail is solely property of the sender's organization, and this mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.
信息安全声明：此电子邮件及其附件包含特权或机密信息。如果您不是预定的收件人，或您是未经授权的人员，请不要阅读、保存、打印、复制、转发、公开或以其他方式使用此电子邮件和附件的信息。本邮件包含信息归发件人所在组织所有，且发件人所在组织对该邮件拥有所有权利。请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分内容。
 
发件人： BORBER
发送时间： 2020-08-02 19:35
收件人： renbaoshuo/baoshuo-blog
抄送： Ren Baoshuo; Author
主题： Re: [renbaoshuo/baoshuo-blog] 友情链接 - 宝硕博客 (#7)
本站标题 BORBER
本站简介 跌宕歌词 纵横书卷 不与遣年华
头像地址 https://cdn.jsdelivr.net/gh/Borber/PublicPic1/headImg/head.png
博客地址 https://borber.cn
已加贵站

**Comment by renbaoshuo** [comment]
> 本站标题 BORBER
> 本站简介 跌宕歌词 纵横书卷 不与遣年华
> 头像地址 https://cdn.jsdelivr.net/gh/Borber/PublicPic1/headImg/head.png
> 博客地址 https://borber.cn
> 已加贵站

@borber 已加，将在下次更新文章时生效。

**Comment by XiaoMouz** [comment]
网站名称：`小莫のBase`
网站地址：`http://blog.mou.best/`
头像链接：`https://s1.ax1x.com/2020/08/07/ah2jqP.jpg`
网站描述：`该笑的时候没有快乐 该哭泣的时候没有眼泪 该相信的时候没有诺言`
已加全站链啦,还有，我这边看你这个评论框是全黑（点开时），根本打不了字- -

**Comment by renbaoshuo** [comment]
> 网站名称：`小莫のBase`
> 网站地址：`http://blog.mou.best/`
> 头像链接：`https://s1.ax1x.com/2020/08/07/ah2jqP.jpg`
> 网站描述：`该笑的时候没有快乐 该哭泣的时候没有眼泪 该相信的时候没有诺言`
> 已加全站链啦,还有，我这边看你这个评论框是全黑（点开时），根本打不了字- -

已加友链，等待生效中。

打字问题是样式错误，已修。

**Comment by Lzc256** [comment]
网站名称：lzcBlog
网站地址：https://www.lzcapp.cn
头像链接：https://cdn.lzcapp.cf/hotlink-ok/icons/favicon.ico
网站描述：一个穷困潦倒苦逼学生的打脸日常 TwT 欢迎来此！

**Comment by True-BANANA** [comment]
网站名称：RenaMoe's Blog
网站地址：https://renamoe.gitee.io
头像链接：https://renamoe.gitee.io/img/avatar.png
网站描述：位于HE的菜鸡OIer
贵站链接已加，将不久后更新

**Comment by renbaoshuo** [comment]
> @True-BANANA
> 网站名称：RenaMoe's Blog
> 网站地址：https://renamoe.gitee.io
> 头像链接：https://renamoe.gitee.io/img/avatar.png
> 网站描述：位于HE的菜鸡OIer
> 贵站链接已加，将不久后更新

请仔细阅读申请须知。

```
申请网站必须使用独立域名，二级域名和免费域名一律无视。
```

**Comment by renbaoshuo** [comment]
> @Lzc256
> 网站名称：lzcBlog
> 网站地址：https://www.lzcapp.cn
> 头像链接：https://cdn.lzcapp.cf/hotlink-ok/icons/favicon.ico
> 网站描述：一个穷困潦倒苦逼学生的打脸日常 TwT 欢迎来此！

拒绝原因

+ 头像请修改 
   *原因：1. 免费域名    2. 清晰度过低*

请仔细阅读申请须知，待修改完成后再次进行提交，谢谢。

**Comment by DevilMayCry2333** [comment]
网站名称：joker的小破站
网站地址：https://blog.youkaiyu.com/
头像链接：https://blog.youkaiyu.com/usr/uploads/common/acc.jpeg
网站描述：一个不知名的人

**Comment by Onism02** [comment]
网站名称：Onismのblog
网站地址：https://onism.moe
头像链接：https://kyun.ltyuanfang.cn/tc/2020/09/15/2dd92d1c2d2c4.jpg
网站描述：我曾拾起一片自认为很独特的叶子，回头一看竟遍地都是。
已添加贵站为全站链接

**Comment by renbaoshuo** [comment]
> @True-BANANA
> 网站名称：RenaMoe's Blog
> 网站地址：https://renamoe.gitee.io
> 头像链接：https://renamoe.gitee.io/img/avatar.png
> 网站描述：位于HE的菜鸡OIer
> 贵站链接已加，将不久后更新

提示：友链规则已更新，您可以再次发起友链添加申请。
